import { useEffect, useRef, useState } from 'react'
import { motion, useScroll, useTransform, useSpring } from 'framer-motion'
import Lenis from 'lenis'
import { ArrowUpRight, Check, Clock, Shield, BadgeCheck, Gauge, Zap, Code2, Layers } from 'lucide-react'

function useSmoothScroll() {
  useEffect(() => {
    const lenis = new Lenis({ duration: 1.3, smoothWheel: true })
    function loop(t) { lenis.raf(t * 1000); requestAnimationFrame(loop) }
    requestAnimationFrame(loop)
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) lenis.stop()
    return () => lenis.destroy()
  }, [])
}
const SplitWords = ({ text, className = '' }) => {
  const ref = useRef(null); const { scrollYProgress } = useScroll({ target: ref, offset: ['start 88%', 'end 60%'] })
  const words = text.split(' '); const ys = words.map((w, i) => useTransform(scrollYProgress, [i / words.length, (i + 1.2) / words.length], ['115%', '0%'], { clamp: true }))
  return <h2 ref={ref} className={className} style={{ margin: 0 }}>{words.map((w, i) => <span key={i} className="wm" style={{ display: 'inline-block', overflow: 'hidden', paddingBottom: '.1em' }} aria-hidden="true"><motion.span style={{ y: ys[i], display: 'inline-block' }}>{w}</motion.span>{'\u00A0'}</span>)}</h2>
}
const Reveal = ({ children, delay = 0 }) => {
  const ref = useRef(null); const { scrollYProgress } = useScroll({ target: ref, offset: ['start 88%', 'end 65%'] })
  const y = useTransform(scrollYProgress, [0, 1], [48, 0]); const o = useTransform(scrollYProgress, [0, .35], [0, 1])
  return <motion.div ref={ref} style={{ y, opacity: o }}>{children}</motion.div>
}
const Magnetic = ({ children, strength = .3 }) => {
  const ref = useRef(null)
  return <motion.div ref={ref} onMouseMove={(e) => { const el = ref.current, r = el.getBoundingClientRect(); el.style.transform = `translate(${(e.clientX - (r.left + r.width / 2)) * strength}px, ${(e.clientY - (r.top + r.height / 2)) * strength}px)` }} onMouseLeave={() => { ref.current.style.transform = 'translate(0,0)' }} style={{ transition: 'transform .4s cubic-bezier(.22,1,.36,1)', display: 'inline-block' }}>{children}</motion.div>
}

const Header = () => <header className="site-header"><div className="header-inner"><a href="#" className="logo">Drift<span>.</span></a><nav><a href="#services">Services</a><a href="#results">Results</a><a href="#pricing">Pricing</a><a href="#process">Process</a><Magnetic><motion.a href="#contact" whileHover={{ scale: 1.05 }} className="btn-cta">Start a project</motion.a></Magnetic></nav></div></header>

const Hero = () => {
  const ref = useRef(null); const { scrollYProgress } = useScroll({ target: ref, offset: ['start start', 'end start'] })
  const y0 = useTransform(scrollYProgress, [0, 1], [0, -120]); const y1 = useTransform(scrollYProgress, [0, 1], [0, 80]); const y2 = useTransform(scrollYProgress, [0, 1], [0, -200])
  const inY = useTransform(scrollYProgress, [0, .5], [0, 120]); const o = useTransform(scrollYProgress, [0, .45], [1, 0])
  return (
    <section ref={ref} className="hero">
      <div className="hero-layers">
        <motion.span className="hl hl1" style={{ y: y0 }}>DRIFT</motion.span>
        <motion.span className="hl hl2" style={{ y: y2 }}><svg style="display:inline-block;width:1em;height:1em;vertical-align:-0.125em" viewBox="0 0 24 24" fill="currentColor"><polygon points="12 2 14 10 22 12 14 14 12 22 10 14 2 12 10 10"/></svg> depth <svg style="display:inline-block;width:1em;height:1em;vertical-align:-0.125em" viewBox="0 0 24 24" fill="currentColor"><polygon points="12 2 14 10 22 12 14 14 12 22 10 14 2 12 10 10"/></svg></motion.span>
        <motion.span className="hl hl3" style={{ y: y1 }}></motion.span>
      </div>
      <motion.div className="hero-inner" style={{ y: inY, opacity: o }}>
        <p className="kicker"><Layers size={12} /> Smooth-scroll & layered depth studio</p>
        <h1><motion.span className="hw" initial={{ opacity: 0, y: 90 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8, ease: [0.16,1,0.3,1], delay: .3 }}>Scroll with</motion.span> <motion.span className="hw accent" initial={{ opacity: 0, y: 90 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8, ease: [0.16,1,0.3,1], delay: .42 }}>momentum.</motion.span></h1>
        <motion.p className="hero-sub" initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .75 }}>Buttery inertia scroll and layered parallax that make every page feel dimensional, fluid and premium.</motion.p>
        <motion.div className="hero-ctas" initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .9 }}>
          <Magnetic><motion.a href="#contact" whileHover={{ scale: 1.06 }} className="btn-primary">Get a free quote <ArrowUpRight size={16} style={{ verticalAlign: 'middle', marginLeft: 4 }} /></motion.a></Magnetic>
          <Magnetic><motion.a href="#pricing" whileHover={{ scale: 1.06 }} className="btn-ghost">See pricing</motion.a></Magnetic>
        </motion.div>
      </motion.div>
    </section>
  )
}
const Stack = () => { const stack = ['Lenis', 'GSAP', 'React', 'framer-motion', 'TypeScript', 'Vite', 'Figma', 'Node.js']; const metrics = [{ icon: <Gauge size={18} />, n: '60fps', l: 'Smooth scroll' }, { icon: <Zap size={18} />, n: '1.0s', l: 'Avg load' }, { icon: <Code2 size={18} />, n: '100', l: 'Core Web Vitals' }, { icon: <BadgeCheck size={18} />, n: 'AA', l: 'Accessible' }]; return <section className="stackband"><div className="wrap"><Reveal><p className="stack-label">Inertia scroll, performance-first</p></Reveal><Reveal delay={.08}><div className="stack-row">{stack.map(s => <span key={s}>{s}</span>)}</div></Reveal><div className="tech-grid">{metrics.map((m, i) => <Reveal key={i} delay={i * .06}><div className="tech-metric">{m.icon}<div><b>{m.n}</b><span>{m.l}</span></div></div></Reveal>)}</div></div></section> }
const RESULTS = [{ n: '+195%', l: 'Time-on-page', tag: 'smooth depth holds attention' }, { n: '+22%', l: 'Conversion lift', tag: 'premium feel builds trust' }, { n: '50+', l: 'Parallax builds shipped', tag: 'immersive brands' }, { n: '0', l: 'Jank / dropped frames', tag: '60fps guarantee' }]
const Results = () => <section className="results" id="results"><div className="wrap"><Reveal><SplitWords text="Smooth is a feature." className="sec-title" /></Reveal><p className="sec-sub">Depth through speed — the difference between a template and a premium brand.</p><div className="results-grid">{RESULTS.map((r, i) => <Reveal key={i} delay={i * .08}><div className="result-card"><div className="result-n">{r.n}</div><div className="result-l">{r.l}</div><div className="result-tag">{r.tag}</div></div></Reveal>)}</div></div></section>
const SERVICES = [{ icon: '01', title: 'Immersive heroes', desc: 'Multi-layer hero depth that adds cinematic space before a word is read.', price: 'from €1,800', time: '1-2 wks' }, { icon: '02', title: 'Editorial scroll', desc: 'Sticky text + parallax scenes for storytelling that holds attention.', price: 'from €4,200', time: '3-4 wks' }, { icon: '03', title: 'Product showcases', desc: 'Layered product pages that feel dimensional and premium.', price: 'from €3,800', time: '3 wks' }, { icon: '04', title: 'Full smooth sites', desc: 'Complete React builds with inertia scroll throughout.', price: 'from €5,600', time: '4-5 wks' }]
const Services = () => <section className="services" id="services"><div className="wrap"><Reveal><SplitWords text="What we build." className="sec-title" /></Reveal><div className="svc-grid">{SERVICES.map((s, i) => <Reveal key={i} delay={i * .08}><motion.div className="service-card" whileHover={{ y: -8, transition: { type: 'spring', stiffness: 300 } }}><div className="num">{s.icon}</div><h3>{s.title}</h3><p>{s.desc}</p><div className="svc-meta"><span className="price">{s.price}</span><span className="time"><Clock size={13} /> {s.time}</span></div><a href="#contact" className="svc-link">Start this →</a></motion.div></Reveal>)}</div></div></section>
const PLANS = [{ name: 'Layer', price: '€1,800', for: 'Hero depth kit', feats: ['1 parallax hero', '2 revision rounds', 'Optimised for speed', '1-2 week delivery'] }, { name: 'Drift', price: '€5,600', for: 'Full smooth site', feats: ['Full parallax site', 'Sticky + editorial scenes', 'Contact / CTA', '3 revision rounds', 'Performance report', '30 days support'] }, { name: 'Signature', price: '€9,500', for: 'Award-level depth', feats: ['Everything in Drift', 'Custom 3D layers', 'Scroll-choreographed', '90 days support'] }]
const Pricing = () => { const [sel, setSel] = useState(1); return <section className="pricing" id="pricing"><div className="wrap"><Reveal><SplitWords text="Clear pricing, smooth delivery." className="sec-title" /></Reveal><div className="plan-grid">{PLANS.map((p, i) => <Reveal key={i} delay={i * .08}><motion.div className={`plan ${i === sel ? 'plan-feat' : ''}`} whileHover={{ y: -6 }} onClick={() => setSel(i)}>{i === sel && <span className="plan-pop">Most chosen</span>}<h3>{p.name}</h3><div className="plan-price">{p.price}</div><div className="plan-for">{p.for}</div><ul>{p.feats.map((f, k) => <li key={k}><Check size={15} /> {f}</li>)}</ul><motion.a href="#contact" className="plan-btn" whileHover={{ scale: 1.04 }}>Choose {p.name}</motion.a></motion.div></Reveal>)}</div><Reveal><div className="guarantee"><Shield size={18} /> Every site ships with a <b>written delivery date</b> and <b>30-day support</b>.</div></Reveal></div></section> }
const PROCESS = [{ n: '01', t: 'Map depth', d: 'We plan the layers that tell your story.', icon: <svg style="display:inline-block;width:1em;height:1em;vertical-align:-0.125em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="1 6 1 22 8 18 16 22 23 18 23 2 16 6 8 2 1 6"/><line x1="8" y1="2" x2="8" y2="18"/><line x1="16" y1="6" x2="16" y2="22"/></svg> }, { n: '02', t: 'Design', d: 'Direction + a scroll prototype you approve.', icon: <svg style="display:inline-block;width:1em;height:1em;vertical-align:-0.125em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="13.5" cy="6.5" r=".5" fill="currentColor"/><circle cx="17.5" cy="10.5" r=".5" fill="currentColor"/><circle cx="8.5" cy="7.5" r=".5" fill="currentColor"/><circle cx="6.5" cy="12.5" r=".5" fill="currentColor"/><path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.926 0 1.648-.746 1.648-1.688 0-.437-.18-.835-.437-1.125-.29-.289-.438-.652-.438-1.125a1.64 1.64 0 011.668-1.668h1.996c3.051 0 5.555-2.503 5.555-5.554C21.965 6.012 17.461 2 12 2z"/></svg> }, { n: '03', t: 'Build', d: 'Inertia scroll + parallax dev, sprint by sprint.', icon: <svg style="display:inline-block;width:1em;height:1em;vertical-align:-0.125em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 00.33 1.82l.06.06a2 2 0 010 2.83 2 2 0 01-2.83 0l-.06-.06a1.65 1.65 0 00-1.82-.33 1.65 1.65 0 00-1 1.51V21a2 2 0 01-4 0v-.09A1.65 1.65 0 009 19.4a1.65 1.65 0 00-1.82.33l-.06.06a2 2 0 01-2.83 0 2 2 0 010-2.83l.06-.06A1.65 1.65 0 004.68 15a1.65 1.65 0 00-1.51-1H3a2 2 0 010-4h.09A1.65 1.65 0 004.6 9a1.65 1.65 0 00-.33-1.82l-.06-.06a2 2 0 012.83-2.83l.06.06A1.65 1.65 0 009 4.68a1.65 1.65 0 001-1.51V3a2 2 0 014 0v.09a1.65 1.65 0 001 1.51 1.65 1.65 0 001.82-.33l.06-.06a2 2 0 012.83 2.83l-.06.06A1.65 1.65 0 0019.4 9a1.65 1.65 0 001.51 1H21a2 2 0 010 4h-.09a1.65 1.65 0 00-1.51 1z"/></svg> }, { n: '04', t: 'Ship', d: 'Launch smooth, measure, refine.', icon: <svg style="display:inline-block;width:1em;height:1em;vertical-align:-0.125em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 00-2.91-.09z"/><path d="M12 15l-3-3a22 22 0 012-3.95A12.88 12.88 0 0122 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 01-4 2z"/><path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0"/><path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5"/></svg> }]
const Process = () => <section className="process" id="process"><div className="wrap"><Reveal><SplitWords text="Depth, layer by layer." className="sec-title" /></Reveal><div className="proc-grid">{PROCESS.map((p, i) => <Reveal key={i} delay={i * .08}><motion.div className="proc-step" whileHover={{ y: -6 }}><div className="proc-num">{p.n}<span>{p.icon}</span></div><h4>{p.t}</h4><p>{p.d}</p></motion.div></Reveal>)}</div></div></section>
const QUOTES = [{ q: "Drift made our site feel expensive. Time-on-page up 195%.", n: 'Nina K.', r: 'CMO, Prisma' }, { q: "The smooth scroll is what everyone notices first. It's flawless on mobile.", n: 'Tom B.', r: 'Founder, Fieldnote' }, { q: "Delivered a parallax showcase that holds 60fps on a mid-range phone. Impressive.", n: 'Iris V.', r: 'Product Lead, Lumen' }]
const Testimonials = () => <section className="quotes"><div className="wrap"><Reveal><SplitWords text="Clients who feel the depth." className="sec-title" /></Reveal><div className="quotes-grid">{QUOTES.map((q, i) => <Reveal key={i} delay={i * .08}><figure className="quote"><div className="stars"><svg style="display:inline-block;width:1em;height:1em;vertical-align:-0.125em" viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" stroke-width="1"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26"/></svg><svg style="display:inline-block;width:1em;height:1em;vertical-align:-0.125em" viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" stroke-width="1"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26"/></svg><svg style="display:inline-block;width:1em;height:1em;vertical-align:-0.125em" viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" stroke-width="1"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26"/></svg><svg style="display:inline-block;width:1em;height:1em;vertical-align:-0.125em" viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" stroke-width="1"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26"/></svg><svg style="display:inline-block;width:1em;height:1em;vertical-align:-0.125em" viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" stroke-width="1"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26"/></svg></div><blockquote>{q.q}</blockquote><figcaption><b>{q.n}</b><span>{q.r}</span></figcaption></figure></Reveal>)}</div></div></section>
const CTA = () => { const [sent, setSent] = useState(false); return <section className="cta" id="contact"><div className="wrap cta-inner"><Reveal><SplitWords text="Make your site feel physical." className="sec-title" /></Reveal><p className="sec-sub">Tell us about your project — a motion plan and fixed quote within one business day.</p>{!sent ? <motion.form className="cta-form" initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} onSubmit={(e) => { e.preventDefault(); setSent(true) }}><div className="form-row"><input required placeholder="Your name" aria-label="Your name" /><input required type="email" placeholder="Work email" aria-label="Work email" /></div><textarea rows="3" placeholder="Tell us about your site" aria-label="Project details" /><Magnetic><motion.button whileHover={{ scale: 1.05 }} className="btn-primary" type="submit" style={{ border: 'none', cursor: 'pointer' }}>Send project brief <ArrowUpRight size={16} style={{ verticalAlign: 'middle', marginLeft: 4 }} /></motion.button></Magnetic><p className="form-note"><Shield size={13} /> Free quote · no obligation · reply within 1 business day</p></motion.form> : <motion.div className="cta-done" initial={{ scale: 0.8, opacity: 0 }} animate={{ scale: 1, opacity: 1 }}><BadgeCheck size={44} /><h3>Brief received <svg style="display:inline-block;width:1em;height:1em;vertical-align:-0.125em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg></h3><p>We'll reply within one business day.</p></motion.div>}<div className="cta-contact"><span>Prefer email?</span> <a href="mailto:hello@drift.design">hello@drift.design</a></div></div></section> }
const Footer = () => <footer className="site-footer"><div className="wrap foot-inner"><span>© 2026 Drift — inertia & parallax.</span><span><a href="#services">Services</a> · <a href="#pricing">Pricing</a> · <a href="mailto:hello@drift.design">hello@drift.design</a></span></div></footer>

export default function App() {
  useSmoothScroll()
  return (<><Header /><Hero /><Stack /><Results /><Services /><Pricing /><Process /><Testimonials /><CTA /><Footer /></>)
}
